module.exports =
  Button: require('./Button.spec')
  # Tile: require('./Tile.spec')
  Icon: require('./Icon.spec')
  Toolbar: require('./Toolbar.spec')
  List: require('./List.spec')
  Tabs: require('./Tabs.spec')
  Checkbox: require('./Checkbox.spec')
  Slider: require('./Slider.spec')
  TextField: require('./TextField.spec')
